server:
  http:
    addr: 0.0.0.0:8004
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9004
    timeout: 1s
client:
  user:
    to: user-service:9001
  publish:
    to: publish-service:9002
data:
  mysql:
    driver: mysql
    dsn: "root:toomanysource@tcp(mysql:3306)/atreus?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    db: 4
    addr: redis:6379
    password: "atreus"
    read_timeout: 0.2s
    write_timeout: 0.2s
    TTL: 1000
  kafka:
    addr: kafka:9092
    video_favorite_topic: "video_favorite"
    user_favorite_topic: "user_favorite"
    author_favorite_topic: "author_favorite"
    partition: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
jwt:
  http:
    token_key: "AtReUs"
  grpc:
    token_key: "ToOMaNySoUrCe"
