server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:toomanysource@tcp(127.0.0.1:33069)/atreus?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    db: 1
    addr: 127.0.0.1:16379
    password: "atreus"
    read_timeout: 0.2s
    write_timeout: 0.2s
    TTL: 1000
  kafka:
    addr: 127.0.0.1:9092
    favorite_topic: "favorite"
    favored_topic: "favored"
    follow_topic: "follow"
    follower_topic: "follower"
    publish_topic: "publish"
    partition: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
jwt:
  http:
    token_key: "AtReUs"
  grpc:
    token_key: "ToOMaNySoUrCe"
