// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	"github.com/toomanysource/atreus/app/user/service/internal/biz"
	"github.com/toomanysource/atreus/app/user/service/internal/conf"
	"github.com/toomanysource/atreus/app/user/service/internal/data"
	"github.com/toomanysource/atreus/app/user/service/internal/server"
	"github.com/toomanysource/atreus/app/user/service/internal/service"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, client *conf.Client, confData *conf.Data, jwt *conf.JWT, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewGormDb(confData, logger)
	redisClient := data.NewRedisConn(confData, logger)
	kfkReader := data.NewKafkaReader(confData)
	dataData, cleanup, err := data.NewData(db, redisClient, kfkReader, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	discovery := server.NewDiscovery(registry)
	relationConn := server.NewRelationClient(discovery, client, logger)
	relationRepo := data.NewRelationRepo(relationConn)
	userUsecase := biz.NewUserUsecase(userRepo, relationRepo, jwt, logger)
	userService := service.NewUserService(userUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	httpServer := server.NewHTTPServer(confServer, jwt, userService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
