// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: favorite/service/v1/favorite.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on IsFavoriteRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IsFavoriteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IsFavoriteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IsFavoriteRequestMultiError, or nil if none found.
func (m *IsFavoriteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IsFavoriteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return IsFavoriteRequestMultiError(errors)
	}

	return nil
}

// IsFavoriteRequestMultiError is an error wrapping multiple validation errors
// returned by IsFavoriteRequest.ValidateAll() if the designated constraints
// aren't met.
type IsFavoriteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IsFavoriteRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IsFavoriteRequestMultiError) AllErrors() []error { return m }

// IsFavoriteRequestValidationError is the validation error returned by
// IsFavoriteRequest.Validate if the designated constraints aren't met.
type IsFavoriteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IsFavoriteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IsFavoriteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IsFavoriteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IsFavoriteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IsFavoriteRequestValidationError) ErrorName() string {
	return "IsFavoriteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e IsFavoriteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIsFavoriteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IsFavoriteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IsFavoriteRequestValidationError{}

// Validate checks the field values on IsFavoriteReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IsFavoriteReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IsFavoriteReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IsFavoriteReplyMultiError, or nil if none found.
func (m *IsFavoriteReply) ValidateAll() error {
	return m.validate(true)
}

func (m *IsFavoriteReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return IsFavoriteReplyMultiError(errors)
	}

	return nil
}

// IsFavoriteReplyMultiError is an error wrapping multiple validation errors
// returned by IsFavoriteReply.ValidateAll() if the designated constraints
// aren't met.
type IsFavoriteReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IsFavoriteReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IsFavoriteReplyMultiError) AllErrors() []error { return m }

// IsFavoriteReplyValidationError is the validation error returned by
// IsFavoriteReply.Validate if the designated constraints aren't met.
type IsFavoriteReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IsFavoriteReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IsFavoriteReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IsFavoriteReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IsFavoriteReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IsFavoriteReplyValidationError) ErrorName() string { return "IsFavoriteReplyValidationError" }

// Error satisfies the builtin error interface
func (e IsFavoriteReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIsFavoriteReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IsFavoriteReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IsFavoriteReplyValidationError{}

// Validate checks the field values on FavoriteListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FavoriteListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FavoriteListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FavoriteListRequestMultiError, or nil if none found.
func (m *FavoriteListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FavoriteListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Token

	if len(errors) > 0 {
		return FavoriteListRequestMultiError(errors)
	}

	return nil
}

// FavoriteListRequestMultiError is an error wrapping multiple validation
// errors returned by FavoriteListRequest.ValidateAll() if the designated
// constraints aren't met.
type FavoriteListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FavoriteListRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FavoriteListRequestMultiError) AllErrors() []error { return m }

// FavoriteListRequestValidationError is the validation error returned by
// FavoriteListRequest.Validate if the designated constraints aren't met.
type FavoriteListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FavoriteListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FavoriteListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FavoriteListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FavoriteListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FavoriteListRequestValidationError) ErrorName() string {
	return "FavoriteListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FavoriteListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFavoriteListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FavoriteListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FavoriteListRequestValidationError{}

// Validate checks the field values on FavoriteListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *FavoriteListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FavoriteListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FavoriteListReplyMultiError, or nil if none found.
func (m *FavoriteListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *FavoriteListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for StatusCode

	// no validation rules for StatusMsg

	for idx, item := range m.GetVideoList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FavoriteListReplyValidationError{
						field:  fmt.Sprintf("VideoList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FavoriteListReplyValidationError{
						field:  fmt.Sprintf("VideoList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FavoriteListReplyValidationError{
					field:  fmt.Sprintf("VideoList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return FavoriteListReplyMultiError(errors)
	}

	return nil
}

// FavoriteListReplyMultiError is an error wrapping multiple validation errors
// returned by FavoriteListReply.ValidateAll() if the designated constraints
// aren't met.
type FavoriteListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FavoriteListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FavoriteListReplyMultiError) AllErrors() []error { return m }

// FavoriteListReplyValidationError is the validation error returned by
// FavoriteListReply.Validate if the designated constraints aren't met.
type FavoriteListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FavoriteListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FavoriteListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FavoriteListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FavoriteListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FavoriteListReplyValidationError) ErrorName() string {
	return "FavoriteListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e FavoriteListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFavoriteListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FavoriteListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FavoriteListReplyValidationError{}

// Validate checks the field values on FavoriteActionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FavoriteActionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FavoriteActionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FavoriteActionRequestMultiError, or nil if none found.
func (m *FavoriteActionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FavoriteActionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetToken()) < 1 {
		err := FavoriteActionRequestValidationError{
			field:  "Token",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetVideoId() <= 0 {
		err := FavoriteActionRequestValidationError{
			field:  "VideoId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ActionType

	if len(errors) > 0 {
		return FavoriteActionRequestMultiError(errors)
	}

	return nil
}

// FavoriteActionRequestMultiError is an error wrapping multiple validation
// errors returned by FavoriteActionRequest.ValidateAll() if the designated
// constraints aren't met.
type FavoriteActionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FavoriteActionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FavoriteActionRequestMultiError) AllErrors() []error { return m }

// FavoriteActionRequestValidationError is the validation error returned by
// FavoriteActionRequest.Validate if the designated constraints aren't met.
type FavoriteActionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FavoriteActionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FavoriteActionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FavoriteActionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FavoriteActionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FavoriteActionRequestValidationError) ErrorName() string {
	return "FavoriteActionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FavoriteActionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFavoriteActionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FavoriteActionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FavoriteActionRequestValidationError{}

// Validate checks the field values on FavoriteActionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FavoriteActionReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FavoriteActionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FavoriteActionReplyMultiError, or nil if none found.
func (m *FavoriteActionReply) ValidateAll() error {
	return m.validate(true)
}

func (m *FavoriteActionReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for StatusCode

	// no validation rules for StatusMsg

	if len(errors) > 0 {
		return FavoriteActionReplyMultiError(errors)
	}

	return nil
}

// FavoriteActionReplyMultiError is an error wrapping multiple validation
// errors returned by FavoriteActionReply.ValidateAll() if the designated
// constraints aren't met.
type FavoriteActionReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FavoriteActionReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FavoriteActionReplyMultiError) AllErrors() []error { return m }

// FavoriteActionReplyValidationError is the validation error returned by
// FavoriteActionReply.Validate if the designated constraints aren't met.
type FavoriteActionReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FavoriteActionReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FavoriteActionReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FavoriteActionReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FavoriteActionReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FavoriteActionReplyValidationError) ErrorName() string {
	return "FavoriteActionReplyValidationError"
}

// Error satisfies the builtin error interface
func (e FavoriteActionReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFavoriteActionReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FavoriteActionReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FavoriteActionReplyValidationError{}

// Validate checks the field values on Video with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Video) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Video with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in VideoMultiError, or nil if none found.
func (m *Video) ValidateAll() error {
	return m.validate(true)
}

func (m *Video) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetAuthor()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VideoValidationError{
					field:  "Author",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VideoValidationError{
					field:  "Author",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuthor()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VideoValidationError{
				field:  "Author",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for PlayUrl

	// no validation rules for CoverUrl

	// no validation rules for FavoriteCount

	// no validation rules for CommentCount

	// no validation rules for IsFavorite

	// no validation rules for Title

	if len(errors) > 0 {
		return VideoMultiError(errors)
	}

	return nil
}

// VideoMultiError is an error wrapping multiple validation errors returned by
// Video.ValidateAll() if the designated constraints aren't met.
type VideoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VideoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VideoMultiError) AllErrors() []error { return m }

// VideoValidationError is the validation error returned by Video.Validate if
// the designated constraints aren't met.
type VideoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VideoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VideoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VideoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VideoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VideoValidationError) ErrorName() string { return "VideoValidationError" }

// Error satisfies the builtin error interface
func (e VideoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVideo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VideoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VideoValidationError{}

// Validate checks the field values on User with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *User) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on User with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in UserMultiError, or nil if none found.
func (m *User) ValidateAll() error {
	return m.validate(true)
}

func (m *User) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for FollowCount

	// no validation rules for FollowerCount

	// no validation rules for IsFollow

	// no validation rules for Avatar

	// no validation rules for BackgroundImage

	// no validation rules for Signature

	// no validation rules for TotalFavorited

	// no validation rules for WorkCount

	// no validation rules for FavoriteCount

	if len(errors) > 0 {
		return UserMultiError(errors)
	}

	return nil
}

// UserMultiError is an error wrapping multiple validation errors returned by
// User.ValidateAll() if the designated constraints aren't met.
type UserMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserMultiError) AllErrors() []error { return m }

// UserValidationError is the validation error returned by User.Validate if the
// designated constraints aren't met.
type UserValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserValidationError) ErrorName() string { return "UserValidationError" }

// Error satisfies the builtin error interface
func (e UserValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUser.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserValidationError{}
