server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
client:
  user:
    to: user-service:9001
  favorite:
    to: favorite-service:9004
data:
  mysql:
    driver: mysql
    dsn: "root:toomanysource@tcp(mysql:3306)/atreus?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    db: 2
    addr: redis:6379
    password: "atreus"
    read_timeout: 0.2s
    write_timeout: 0.2s
    TTL: 1000
  kafka:
    addr: kafka:9092
    comment_topic: "comment"
    favorite_topic: "video_favorite"
    publish_topic: "publish"
    partition: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
jwt:
  http:
    token_key: "AtReUs"
  grpc:
    token_key: "ToOMaNySoUrCe"
minio:
  endpointExtra: 192.168.124.102:19000
  endpointIntra: minio:9000
  #  Need have 8 character
  accessKeyId: "toomanysource"
  accessSecret: "toomanysource"
  useSSL: false
  bucketName: "oss"