// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	"github.com/toomanysource/atreus/app/publish/service/internal/biz"
	"github.com/toomanysource/atreus/app/publish/service/internal/conf"
	"github.com/toomanysource/atreus/app/publish/service/internal/data"
	"github.com/toomanysource/atreus/app/publish/service/internal/server"
	"github.com/toomanysource/atreus/app/publish/service/internal/service"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, client *conf.Client, minio *conf.Minio, jwt *conf.JWT, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewMysqlConn(confData)
	extraConn := data.NewMinioExtraConn(minio)
	intraConn := data.NewMinioIntraConn(minio)
	minioXClient := data.NewMinioConn(minio, extraConn, intraConn)
	writer := data.NewKafkaWriter(confData)
	kfkReader := data.NewKafkaReader(confData)
	dataData, cleanup, err := data.NewData(db, minioXClient, writer, kfkReader, logger)
	if err != nil {
		return nil, nil, err
	}
	userConn := server.NewUserClient(client, logger)
	favoriteConn := server.NewFavoriteClient(client, logger)
	publishRepo := data.NewPublishRepo(dataData, userConn, favoriteConn, logger)
	publishUsecase := biz.NewPublishUsecase(publishRepo, logger)
	publishService := service.NewPublishService(publishUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, publishService, logger)
	httpServer := server.NewHTTPServer(confServer, jwt, publishService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
